[project]
name = "telecom-egypt-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "easyocr>=1.7.2",
    "fastapi>=0.140.1",
    "faster-whisper>=1.2.1",
    "langdetect>=1.0.9",
    "pdf2image>=1.17.0",
    "piper-tts>=1.6.0",
    "playwright>=1.61.0",
    "pypdf>=6.14.2",
    "python-docx>=1.2.0",
    "qdrant-client>=1.18.0",
    "requests>=2.34.2",
    "streamlit>=1.60.0",
    "uvicorn>=0.51.0",
]
